{{- if .Values.ingress.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-ingressroute
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ .Values.ingress.apiHost }}`)
      kind: Rule
      services:
        - name: {{ .Release.Name }}-backend-service
          port: 8080
    - match: Host(`{{ .Values.ingress.host }}`)
      kind: Rule
      services:
        - name: {{ .Release.Name }}-frontend-service
          port: {{ .Values.frontend.service.port }}
{{- end }}