apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres-service
spec:
  type: {{ .Values.postgres.service.type }}
  selector:
    app: {{ .Release.Name }}-postgres
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432