apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: family-heritage-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/musmike/family-heritage-gitops.git'
    targetRevision: main
    path: charts/family-heritage-chart
    helm:
      releaseName: prod
      valueFiles:
        - ../../apps/production/values-prod.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true