apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: family-heritage-dev
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: |
      backend=twoj-registry/backend:~dev,
      frontend=twoj-registry/frontend:~dev
    
    argocd-image-updater.argoproj.io/backend.update-strategy: latest
    argocd-image-updater.argoproj.io/frontend.update-strategy: latest
    
    argocd-image-updater.argoproj.io/write-back-method: argocd
    
    argocd-image-updater.argoproj.io/backend.pull-secret: pullsecret:argocd/registry-creds
    argocd-image-updater.argoproj.io/frontend.pull-secret: pullsecret:argocd/registry-creds
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/musmike/family-heritage-gitops.git'
      targetRevision: main
      path: envs/dev
      ref: values
      directory:
        include: '*.yaml'

    - repoURL: 'https://github.com/musmike/family-heritage-gitops.git'
      targetRevision: main
      path: charts/family-heritage
      helm:
        releaseName: dev
        valueFiles:
          - $values/envs/dev/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true