postgres:
  existingSecret: postgres-secret-staging-dev
  
backend:
  existingSecret: backend-secret-staging-dev
  image:
    tag: "staging-dev-build"
  springProfile: staging-dev

frontend:
  image:
    tag: "staging-dev-build"

ingress:
  enabled: true

importSecrets:
  - name: "{{ .Release.Name }}-values-secrets"
    importKeys:
      - values.yaml