apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eso-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/musmike/family-heritage-gitops.git'
    targetRevision: main
    path: eso/
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true